### ISSUE TITLE
[Milestone] 프로젝트 마일스톤을 위한 요구사항들 정리

### ISSUE THREAD

**Issue by JangHanjun** [JangHanjun/UE5_Practice#1]
## 개요

본 프로젝트는 언리얼의 숙련도를 높이기 위한 프로젝트로 '좀비를 해치우면서 벗어나고 강해지는' 시스템을 가진 게임을 만드는 것이 목표입니다. 개발 기간은 약 2~3개월로 잡고 있으며 이에 따라 마일스톤의 대략적인 부분을 이슈에 남겨 전체 일정을 관리하려고 합니다.

## 필요 기능들 목록
간략하게 정리해 봅니다.

### 플레이어 관련
- [ ] 플레이어는 WASD 움직임이 가능하고 점프를 할 수 있습니다.
- [ ] 무기를 들어 공격을 할 수 있습니다.
- [ ] 무기의 종류는 칼, 활이며 그 외의 무기들은 플레이어가 직접 조작하는 무기들이 아닙니다.
- [ ] 좀비를 죽일 때마다 경험치를 쌓을 수 있습니다.
- [ ] 쌓은 경험치를 통해 NPC 에게 말을 걸면 잠시 게임 시간이 멈추고 능력치 향상을 할 수 있습니다.
- [ ] 좀비에게 피격당하면 체력이 줄어들고 체력이 0 이하가 되면 죽습니다.

### 적 관련
- [ ] 좀비들은 스폰이 되면 순찰 상태(Idle)가 됩니다.
- [ ] 순찰 상태에서 시야에 플레이어가 들어오게 되면 플레이어에게 접근합니다.
- [ ] 순찰 상태에서 데미지를 입으면 플레이어에게 접근합니다
- [ ] 플레이어가 근처에 오면 공격해 피해를 입힙니다.
- [ ] 좀비는 데미지를 받을 수 있으며 체력이 0 이하가 되면 죽게 됩니다.
- [ ] 이와 관련해서 오브젝트 풀링을 구현해 좀비를 관리하게 됩니다.
- [ ] 보스 좀비의 경우 체력이 더 많고 움직임이 느립니다.
- [ ] 보스의 공격 판정이 들어가게 되면 공격 컷씬이 나오게 됩니다. 이동안 프레이어는 다른 좀비들의 공격을 받지 않고 일부 시간 무적이 됩니다.

### NPC 관련
- [ ] NPC에게 말을 걸면 플레이어를 강화할 수 있는 메뉴가 나오게 됩니다.

### UI 관련
- [ ] ESC를 누르면 인게임 UI가 나옵니다.
- [ ] 인게임 UI는 게임으로, 메인 메뉴로, 음량 조절, 감도 조절 등의 메뉴들이 들어가게 됩니다.
- [ ] 인게임 메뉴가 활성화된 시점에는 게임 내 시간이 흐르지 않습니다.
- [ ] 메인 메뉴에는 게임 시작, 플레이어가 모은 경험치를 쓸 수 있는 메뉴, 환경설정 등의 메뉴가 있습니다.

### 그 외 요구사항들
- [ ] 플레이어는 로그라이트 형식을 따라가며 게임 내 경험치를 통해 초기 능력을 강화할 수 있습니다.
- [ ] 좀비는 스테이트 패턴을 통해서 제작합니다.

## 마무리

일단 22년 11월 7일을 기준으로 작성하게 된 요구사항들로 일단 22년 12월 말 1차 릴리즈를 하는것이 목표입니다.
